### ISSUE TITLE
Compilation on a 32-bit Ubuntu 18.04 

### ISSUE THREAD

**Issue by aabbtree77** [hyprspace/hyprspace#94]
This is not an issue, but more like some brief memo in case someone or me in the future has to run hyprspace on a 32 bit system.

Running "sudo curl -L https://hyprspace.io/install.sh | bash" does not work on my 32 bit Ubuntu 18.04 machine as there seem to be no binaries provided.

After git-cloning the source code and running "go build" the compilation halts with
```
# github.com/lucas-clemente/quic-go/internal/qtls
../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.24.0/internal/qtls/go118.go:6:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
```
BTW, this takes place in both, 32 bit and 64 bit systems.

Inside go.mod I made the following changes:

go 1.16 => go 1.19

github.com/libp2p/go-libp2p v0.17.0 => github.com/libp2p/go-libp2p v0.22.0 

Afterwards
```
go get -u
go mod tidy
go build
```
halts again, this time with
```
../go/pkg/mod/github.com/ipfs/go-ipns@v0.1.2/record.go:49:19: undefined: peer.IDFromString
yoko@yoko:~/hyprspace$ sudo gedit ../go/pkg/mod/github.com/ipfs/go-ipns@v0.1.2/record.go
```
Edit the corresponding "record.go file" according to the changes in 

https://github.com/ipfs/go-ipns/pull/38/files/3d7f9c2eccc1bcf3ba6dbe543766a49743c546bd

and run
```
go build
```

This finally produces a neat hyprspace binary of size 33.5MB.

I have tested hyprspace in three situations connecting PCA to PCB:
- [x] LAN: ping and ssh work fine.
- [x] PCA is on a mobile hotspot from "telia.lt wireless ISP", PCB - "skynet.lt wired ISP": Everything's fine too!
- [ ] PCA on "telia.lt wireless ISP", PCB - "mezon.lt wireless ISP": No luck :(.

In the last setup PCB is behind some complicated four-router "relay", though this should not be a problem as we do not need any port forwarding with hyprspace (Remmina and port forwarding did not work there), most likely some nasty symmetric NAT or something.

In any case, 2 out of 3 is not a bad result for these "behind unknown assume the worse NAT" cases. I am also trying another "spiritual brother" to this Go code:

https://github.com/mudler/edgevpn/issues/25 

I did not succeed with the first run there, but I intend to make some further tests and report back how that runs in all three cases and if there is a winner here, though that third case looks hopeless, i.e. changing ports from 8001 to 443 as suggested in some other issues here did not work, unfortunately.

In any case, thank you for your amazing work, stumbled on hyprspace almost by accident after a long tedious search on github, thinking first that there must be some better "direct p2p way" to solve my permanent Remmina/TeamViewer headaches, then finding go-libp2p and IPFS and not knowing how to approach any of these big concepts/systems. 

I could add that it is very tedious to investigate these networking tools as all the landing pages look like commercial SaaS adds missing some key first priority detail: If the thing needs any distant 3rd party service or is itself a service, or just an OSS code that yet still relies on a "rendezvous server" somewhere inside, if any extra VM, any fixed IP is involved... vs. a totally clean P2P ideal thing such as Transmission BitTorrent client of my Ubuntu machine... 

What helped me immensely here is the intro video with a precise set up and "Use Cases" section which revealed me that I can use this VPN to ssh globally from anywhere to my LAN/PC.
